---
- name: latest mariadb version installed
  dnf:
    name: mariadb,mariadb-server
    state: latest

- name: mariadb enabled and running
  service:
    name: mariadb
    enabled: true
    state: started

- name: open firewall
  ansible.posix.firewalld:
    service: mysql
    permanent: yes
    state: enabled

- name: set the root user passwd
  mysql_user:
  community.mysql.mysql_user:
    host_all: true
    name: "root"
    password: "{{ mysql_root_password }}"
    state: present
    