---
- name: latest mariadb version installed
  dnf:
    name: mariadb,mariadb-server
    state: latest

- name: mariadb enabled and running
  service:
    name: mariadb
    enabled: true
    state: started

- name: open firewall
  ansible.posix.firewalld:
    service: mysql
    permanent: yes
    state: enabled

- name: Set the root user passwd
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    login_passwrd: ''
    name: "root"
    password: "{{ mysql_root_password }}"
    state: present

- name: create my.cnf with db credentials
  ansible.builtin.template:
    src: .my.cnf.j2
    dest: /root/.my.cnf

- name: remove external access root accounts
  community.mysql.mysql_query:
    query: DELETE FROM mysql.user WHERE USER='root' AND HOST NOT IN ('localhost','127.0.0.1','::1')

- name: remove all anonymous accounts
  community.mysql.mysql_user:
    name: ""
    host_all: yes
    state: absent

- name: remove test db
  community.mysql.mysql_db:
    name: test
    state: absent