---
- name: latest mariadb version installed and depend
  dnf:
    name: mariadb-server,python3-PyMySQL
    state: latest

- name: mariadb enabled and running
  service:
    name: mariadb
    enabled: true
    state: started

- name: open firewall
  ansible.posix.firewalld:
    service: mysql
    permanent: yes
    state: enabled

- name: Set the root user password
  community.mysql.mysql_user:
    host_all: true
    name: "root"
    password: "{{ mysql_root_password }}"
    state: present

- name: create my.cnf with db credentials
  ansible.builtin.template:
    src: .my.cnf.j2
    dest: /root/.my.cnf

- name: remove all anonymous accounts
  community.mysql.mysql_user:
    name: ""
    host_all: yes
    state: absent

- name: remove test db
  community.mysql.mysql_db:
    name: test
    state: absent