---
- name: latest mariadb version installed and depend
  ansible.builtin.dnf:
    name: mariadb-server,python3-PyMySQL
    state: latest

- name: mariadb enabled and running
  service:
    name: mariadb
    enabled: true
    state: started

- name: open firewall
  ansible.posix.firewalld:
    zone: public
    port: 3306/tcp
    permanent: true
    state: enabled

- name: reload firewall
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded

- name: Set the root user password
  community.mysql.mysql_user:
    host_all: true
    name: "root"
    password: "{{ mysql_root_password }}"
    state: present

- name: create my.cnf with db credentials
  ansible.builtin.template:
    src: .my.cnf.j2
    dest: /root/.my.cnf

- name: remove all anonymous accounts
  community.mysql.mysql_user:
    name: ""
    host_all: yes
    state: absent

- name: remove test db
  community.mysql.mysql_db:
    name: test
    state: absent

- name: create database app_db
  community.mysql.mysql_db:
    name: app_db
    state: present

- name: create user app_user
  community.mysql.mysql_user:
    host: webserver
    name: app_user
    password: "Chaslo0987"
    state: present
    priv:
      "app_db.*": "ALL,GRANT"