---
- name: Latest apache version installed
  dnf:
    name: httpd
    state: latest

- name: Apache enabled and running
  service:
    name: httpd
    enabled: true
    state: started

- name: install podman
  dnf:
    name: podman
    state: latest

- name: enable codeready-builder repo
  community.general.rhsm_repository:
    name: codeready-builder-for-rhel-8-x86_64-rpms
    state: enabled

- name: podman enabled and running
  service:
    name: podman
    enabled: true
    state: started

